# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9d898dabf68773cff960cd516d249d6e96c04c909592c4e17ddb3a83b9c3f43ac6bfcd7eaa075fc19ea2f1109c52c611a85f444d1b5470b462ad22b87ebedeeb

test:
  secret_key_base: 46387c1ade49e6498a99a9a8bbf49b7d569ff37fff16803c4a4f8853a7d97657519b20787e2aa2de7c0e2438ef7013d4064c0da785ceae2f892cd020091ddd88

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
